manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: crouchers                         # added
      url-base: https://github.com/crouchers  # added

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: nice-view-mod                 # added
      remote: gpeye                       # added
      revision: main                      # added
  self:
    path: config
